In [2]:
#Q1: Create two arrays of the same size and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([2, 4, 5, 8, 10])

print("Addition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr1 - arr2)

print("\nMultiplication:")
print(arr1 * arr2)

print("\nDivision:")
print(arr1 / arr2)

Addition:
[12 24 35 48 60]

Subtraction:
[ 8 16 25 32 40]

Multiplication:
[ 20  80 150 320 500]

Division:
[5. 5. 6. 5. 5.]


In [9]:
#Q2: Perform matrix multiplication (dot product) between two 2D arrays using np.dot() and the @ operator.

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A :")
print(A,"\n")

print("Matrix B:")
print(B,"\n")

print("Dot Product Of A and B is :")
print(np.dot(A,B),"\n")

print(A @ B)

Matrix A :
[[1 2]
 [3 4]] 

Matrix B:
[[5 6]
 [7 8]] 

Dot Product Of A and B is :
[[19 22]
 [43 50]] 

[[19 22]
 [43 50]]


In [16]:
#Q3: Create an array of 20 random integers and calculate its mean, median, standard deviation, and variance.

array = np.random.randint(0,50,20)

print(array,"\n")

mean = np.mean(array)
print(mean,"\n")

median = np.median(array)
print(median,"\n")

std = np.std(array)
print(std,"\n")

var = np.var(array)
print(var,"\n")

[29  1 41 29 47 12 33 23 38 28 34 21  8  8 20 11 14 34 13 36] 

24.0 

25.5 

12.461942063739505 

155.3 



In [27]:
#Q4: Find the minimum, maximum, and their index positions in a 1D array using argmin() and argmax()

array = np.array([1,2,3,4,5,6,7,8,9])

print("Maximum :",array.max(),"\n")

print("Minimum :",array.min(),"\n")

print("Index of Maximum")
print(np.argmax(array),"\n")


print("Index of Min")
print(np.argmin(array))

Maximum : 9 

Minimum : 1 

Index of Maximum
8 

Index of Min
0


In [35]:
#Q5: Create a 2D array and calculate the sum along rows (axis=1) and along columns (axis=0).

array = np.array([[1,2,3],
                  [5,7,3]])

print(array,"\n")

print("Sum along rows :")
print(np.sum(array,axis=1),"\n")

print("Sum along Column :")
print(np.sum(array,axis=0))

[[1 2 3]
 [5 7 3]] 

Sum along rows :
[ 6 15] 

Sum along Column :
[6 9 6]


In [49]:
#Q6: Generate a random array of 15 values and sort it in ascending and descending order.

array = np.random.randint(0,20,15)

print(array,"\n")

print("Ascending :")
ascending = np.sort(array)
print(ascending,"\n")

print("Dscending :")
decending = np.sort(array)[::-1]
print(decending)

[13  9  0  0 18  9 11  8 13 13  8  6  2  1  4] 

Ascending :
[ 0  0  1  2  4  6  8  8  9  9 11 13 13 13 18] 

Dscending :
[18 13 13 13 11  9  9  8  8  6  4  2  1  0  0]


In [58]:
#Q7: Create an array of angles in degrees and calculate their sine, cosine, and tangent using NumPy

angles = np.array([0,30,45,60,90])

radian = (np.radians(angles))

print("Sine :")
print(np.sin(radian),"\n")

print("Cos :")
print(np.cos(radian),"\n")

print("Tan :")
print(np.tan(radian))

Sine :
[0.         0.5        0.70710678 0.8660254  1.        ] 

Cos :
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17] 

Tan :
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [6]:
#Q8: Compute the cumulative sum and cumulative product of an array using cumsum() and cumprod().

import numpy as np

array = np.array([1,2,3,4,5,6,7,8])

cumulative_sum = np.cumsum(array)

print("cumulative sum :")
print(cumulative_sum,"\n")


cumulative_product = np.cumprod(array)

print("cumulative product :")
print(cumulative_product)



cumulative sum :
[ 1  3  6 10 15 21 28 36] 

cumulative product :
[    1     2     6    24   120   720  5040 40320]


In [12]:
#Q9: Create two arrays and calculate the correlation coefficient between them using np.corrcoef()

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([15, 25, 35, 45, 55])

correlation = np.corrcoef(arr1,arr2)

print(correlation)

[[1. 1.]
 [1. 1.]]


In [15]:
#Q11: Create a 1D array and count how many elements are above the mean value.
array = np.random.randint(0,20,10)

print(array)

mean = np.mean(array)

print(mean)

count = np.sum(array > mean)
print(count)

[14  4 19  3 15  5  0  4 15  9]
8.8
5


In [21]:
#Q13: Create a random 5x5 matrix and calculate its determinant and inverse using np.linalg.

array = np.random.randint(0,20,(5,5))

print(array,"\n")

det = np.linalg.det(array)
print(det,"\n")

inv = np.linalg.inv(array)
print(inv)

[[ 4 14  5  4 17]
 [15 13  3  3 18]
 [ 7 18  7 18 12]
 [14 15 11  1 14]
 [12  0 10 19  2]] 

401912.9999999999 

[[-0.09584164  0.07056005  0.00792709  0.01878765  0.00053743]
 [-0.08431676 -0.00708362  0.0885938   0.04518888 -0.06743997]
 [ 0.07458331 -0.10350748 -0.04791335  0.07759142  0.04194938]
 [ 0.00790718  0.00804154  0.02727954 -0.04708482  0.02633157]
 [ 0.12701505  0.01778246 -0.06715135 -0.05337722  0.03687863]]


In [23]:
#Q14: Generate two random arrays and calculate the Euclidean distance between them.

arr1 = np.random.randint(1, 10, 5)
arr2 = np.random.randint(1, 10, 5)

distance = np.linalg.norm(arr1 -arr2)
print(distance)

9.486832980505138
