In [12]:
# Matrix Operations

import numpy as np

A = np.array([[[1,2,3],
             [5,6,7],
             [4,7,2]]])

B = np.array([[[5,2,9],
             [1,2,4],
             [3,8,2]]])

print("Matrix A is :")
print(A,"\n")

print("Matrix B is :")
print(B,"\n")



Matrix A is :
[[[1 2 3]
  [5 6 7]
  [4 7 2]]] 

Matrix B is :
[[[5 2 9]
  [1 2 4]
  [3 8 2]]] 



In [13]:
print("Addition :")
print(A+B)

Addition :
[[[ 6  4 12]
  [ 6  8 11]
  [ 7 15  4]]]


In [14]:
print("Subtraction :")
print(A-B)

Subtraction :
[[[-4  0 -6]
  [ 4  4  3]
  [ 1 -1  0]]]


In [ ]:
print("Element wise Multiplication :")
print(A*B)

Multiplication :
[[[ 5  4 27]
  [ 5 12 28]
  [12 56  4]]]


In [16]:
print("Matrix wise Multiplication :")
print(A@B)

Matrix wise Multiplication :
[[[16 30 23]
  [52 78 83]
  [33 38 68]]]


In [17]:
print("Transpose :")
print(A.T)

Transpose :
[[[1]
  [5]
  [4]]

 [[2]
  [6]
  [7]]

 [[3]
  [7]
  [2]]]


In [20]:
print("Max :")
print(A.max(),"\n")

print("Min :")
print(A.min())

Max :
7 

Min :
1


In [22]:
print("Sum of Elements :",A.sum())

Sum of Elements : 37


In [23]:
print("Average  :",A.mean())

Average  : 4.111111111111111


In [25]:
print("Row wise Maximum :")
print(A.max(axis = 1))

Row wise Maximum :
[[5 7 7]]


In [26]:
print("Column wise Maximum :")
print(A.max(axis = 0))

Column wise Maximum :
[[1 2 3]
 [5 6 7]
 [4 7 2]]


In [27]:
print("Reshape :")
print(A.reshape(1,9))

Reshape :
[[1 2 3 5 6 7 4 7 2]]


In [28]:
print("Flatten :")
print(A.flatten())

Flatten :
[1 2 3 5 6 7 4 7 2]
