In [12]:
#Q1: Import NumPy and create a 1D array from a Python list of 10 integers. Print its shape, size, and dtype.

import numpy as np

list = [1,2,3,4,5,6,7,8,9,10]

list = np.array([list])

print(type(list))

print(list.shape)

print(list.size)

print(list.dtype)



<class 'numpy.ndarray'>
(1, 10)
10
int64


In [20]:
#Q2: Create a NumPy array of zeros of shape (3,4), an array of ones of shape (2,5), and an identity matrix of
#    size 4.

import numpy as np

zeros_array = np.zeros((3,4))

ones_array = np.ones((2,5))

identity_matrix = np.eye(4)

print("zeros_array :")

print(zeros_array,"\n")

print("ones_array :")

print(ones_array,"\n")

print("identity_matrix :")

print(identity_matrix)

zeros_array :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

ones_array :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

identity_matrix :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
#Q3: Create an array using np.arange(0, 50, 5) and reshape it into a suitable 2D shape.

import numpy as np

arr = np.arange(0,50,5)

print("Original Array :")

print(arr,"\n")

arr2 = arr.reshape(2,5)

print("Reshaped Array :")

print(arr2)

Original Array :
[ 0  5 10 15 20 25 30 35 40 45] 

Reshaped Array :
[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [33]:
#Q4: Generate 10 evenly spaced numbers between 0 and 100 using np.linspace().

array = np.linspace(0,100,10)

print(array)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [38]:
#Q5: Create a 1D array of 20 numbers and extract elements from index 5 to 15 using slicing.

array = np.arange(0,21,1)

result = array[5:15]

print("Original Array")

print(array,"\n")

print("Sliced Array")

print(result)

Original Array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

Sliced Array
[ 5  6  7  8  9 10 11 12 13 14]


In [51]:
#Q6: Create a 2D array (4x4) and access a specific row, a specific column, and a sub-matrix using slicing.

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
                
print("Second Row :")
print(arr[1],"\n")

print("Third Coloumn :")
print(arr[:,2],"\n")

"""      Row    coloumn"""
print(arr[1:3 , 1:3])

Second Row :
[5 6 7 8] 

Third Coloumn :
[ 3  7 11 15] 

[[ 6  7]
 [10 11]]


In [65]:
#Q7: Create a 5x5 array of random integers between 1 and 100. Print the first two rows and last two columns.

arr = np.random.randint(1,100,(5,5))

print(arr,"\n")

print(arr[0:2],"\n")

print(arr[:,3:5])

[[62 15 37 26 81]
 [69 68 89 68 67]
 [76 93 89 74 64]
 [64 76 10 99 20]
 [49 90 45  1 30]] 

[[62 15 37 26 81]
 [69 68 89 68 67]] 

[[26 81]
 [68 67]
 [74 64]
 [99 20]
 [ 1 30]]


In [67]:
#Q8: Reverse a 1D NumPy array without using a loop.

arr = [1,2,3,4,5,6,7,8]

arr = np.array(arr)

print(arr[::-1])

[8 7 6 5 4 3 2 1]


In [68]:
#Q9: Create a 3x3 array and use boolean indexing to extract all elements greater than 5.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr[arr>5]

print(result)

[6 7 8 9]


In [76]:
#Q10: Create two arrays of the same shape and stack them vertically and horizontally.

arr1 = np.array([[1,2,3],
                [4,5,6]])

arr2 = np.array([[2,5,7],
                [3,8,9]])

print(arr1,"\n")

print(arr2,"\n")

V_stack = np.vstack((arr1,arr2))

print(V_stack,"\n")

H_stack = np.hstack((arr1,arr2))

print(H_stack)

[[1 2 3]
 [4 5 6]] 

[[2 5 7]
 [3 8 9]] 

[[1 2 3]
 [4 5 6]
 [2 5 7]
 [3 8 9]] 

[[1 2 3 2 5 7]
 [4 5 6 3 8 9]]


In [80]:
#Q11: Split a 1D array of 12 elements into 3 equal parts using np.split().

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

split = np.split(arr,3)

print("\n",split)


 [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [83]:
#Q12: Create a 1D array and use fancy indexing to select elements at positions [0, 2, 4, 6].

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

result = arr[[0,2,4,6]]

print(result)

[1 3 5 7]


In [90]:
#Q13: Create a 4x4 array and replace all values greater than 10 with 0 using conditional indexing.

arr = np.random.randint(1,100,(4,4))

arr[arr>10] = 0

print(arr)

[[0 6 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 9 0 0]]


In [ ]:
#Q14: Flatten a 2D array into 1D using both ravel() and flatten(), and explain the difference.

"""Ravel()
Returns a view of the original array (if possible).
It does not create a new copy.
If you modify the result, the original array may also change.
It is faster and uses less memory.


flatten()
Returns a copy of the original array.
It creates a new array.
If you modify the result, the original array does not change.
It uses more memory."""

arr = np.random.randint(1,20,(2,2))

print(arr,"\n")

result1 = arr.ravel()

result2 = arr.flatten()

print(result2,"\n")

print(result1)

[[ 1 11]
 [18 15]] 

[ 1 11 18 15] 

[ 1 11 18 15]


In [106]:
#Q15: Create a NumPy array with np.arange(1,17) and reshape it into a 4x4 matrix. Transpose it.

arr = np.arange(1,17)

print(arr,"\n")

result = np.reshape(arr,(4,4))

transpose = result.T

print("Reshaped :")

print(result,"\n")

print("Transpose :")

print(transpose)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] 

Reshaped :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

Transpose :
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
